name: 🐛 Rapport de bogue
description: Signaler un bogue. Si ce n'est pas un bogue, choisissez un autre type d'issue.
title: "[Bogue] "
labels: ["bogue"]
body:
  - type: markdown
    attributes:
      value: |
        ## Rapport de bogue
        Veuillez fournir autant de détails que possible pour nous aider à reproduire et corriger le problème.
  - type: textarea
    id: what-happened
    attributes:
      label: Que s'est-il passé ?
      description: Une description claire et concise du bogue.
      placeholder: "Décrivez le bogue ici..."
    validations:
      required: true
  - type: textarea
    id: additional-description
    attributes:
      label: Description supplémentaire
      description: Tout contexte supplémentaire ou étapes pour reproduire.
      placeholder: "Ajoutez plus de détails..."
  - type: textarea
    id: screenshots
    attributes:
      label: Ajouter des captures d'écran
      description: Si applicable, ajoutez des captures d'écran pour aider à expliquer votre problème.
      placeholder: "Glissez-déposez des images ici ou collez des liens."
  - type: dropdown
    id: browsers
    attributes:
      label: Sur quels navigateurs voyez-vous le problème ?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Brave
        - Microsoft Edge
        - Autre
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Liste de contrôle
      options:
        - label: J'ai vérifié les issues existantes
          required: true
        - label: J'ai lu les directives de contribution
          required: true
        - label: J'accepte de suivre le code de conduite du projet
          required: true
        - label: Je veux travailler sur cette issue
          required: false
