name: Bug Report
description: File a bug report. If this isn't a bug, choose a different issue type.
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Please provide as much detail as possible to help us reproduce and fix the issue.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: "Describe the bug here..."
    validations:
      required: true
  - type: textarea
    id: additional-description
    attributes:
      label: Additional description
      description: Any extra context or steps to reproduce.
      placeholder: "Add more details..."
  - type: textarea
    id: screenshots
    attributes:
      label: Add screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: "Drag and drop images here or paste links."
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Brave
        - Microsoft Edge
        - Other
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have checked the existing issues
          required: true
        - label: I have read the Contributing Guidelines
          required: true
        - label: I agree to follow this project's Code of Conduct
          required: true
        - label: I want to work on this issue
          required: false
