name: Documentation Update
description: Improve or update the project documentation.
title: "[Docs] "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        ## Documentation Update
        Suggest changes or additions to the docs.
  - type: textarea
    id: current-docs
    attributes:
      label: Current Documentation
      description: Describe the existing documentation that needs updating.
      placeholder: "Link to the section or file..."
    validations:
      required: true
  - type: textarea
    id: proposed-changes
    attributes:
      label: Proposed Changes
      description: What should be added, removed, or modified?
      placeholder: "Detailed suggestions..."
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Why is this update needed? Any references?
      placeholder: "Provide context..."
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have checked the existing issues
          required: true
        - label: I have read the Contributing Guidelines
          required: true
        - label: I agree to follow this project's Code of Conduct
          required: true
