name: ➕ Ajout de projet
description: Ajouter un nouveau projet à la liste.
title: "[Projet] "
labels: ["ajout-projet"]
body:
  - type: markdown
    attributes:
      value: |
        ## Ajout de projet
        Suggérer d'ajouter un nouveau projet ou élément.
  - type: input
    id: project-name
    attributes:
      label: Nom du projet
      description: Nom du projet à ajouter.
      placeholder: "ex. : Mon Application"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Description détaillée du projet.
      placeholder: "Que fait-il ? Pourquoi l'ajouter ?"
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: URL du projet
      description: Lien vers le projet (si applicable).
      placeholder: "https://exemple.com"
  - type: checkboxes
    id: terms
    attributes:
      label: Liste de contrôle
      options:
        - label: J'ai vérifié si ce projet existe déjà
          required: true
        - label: J'ai lu les directives de contribution
          required: true
        - label: J'accepte de suivre le code de conduite du projet
          required: true
