name: Report a Security Vulnerability
description: Privately report a security vulnerability.
title: "[Security] "
labels: ["security"]
body:
  - type: markdown
    attributes:
      value: |
        ## Security Vulnerability Report
        Use this to report vulnerabilities. For private reports, consider using GitHub's security advisories.
  - type: textarea
    id: vulnerability-description
    attributes:
      label: Vulnerability Description
      description: A clear description of the vulnerability.
      placeholder: "Details without exposing sensitive info..."
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce it?
      placeholder: "Step 1: ..."
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could be exploited?
      placeholder: "Severity level, affected components..."
  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix
      description: Any ideas for mitigation?
      placeholder: "Optional suggestions..."
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have checked the existing security advisories
          required: true
        - label: I have read the Contributing Guidelines
          required: true
        - label: I agree to follow this project's Code of Conduct
          required: true
